spring.application.name=project-service

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# SERVER CONFIGURATION
server.port=${PORT}
server.servlet.context-path=/

# DATASOURCE
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# SWAGGER / OPENAPI DOCS
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

#JWT CONFIGURATION
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWKS_URL}
app.jwt.issuer=${JWT_ISSUER}

# LOGGING
logging.level.com.kaditsm.project=DEBUG
logging.level.org.springframework.security=DEBUG

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always