name: CI/CD Pipeline - KadITSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose -f /opt/kaditsm/docker-compose.yml up -d --build
