name: Deploy Tenant Service

on:
    push:
        branches:
            - main
        paths:
            - "api/v1/tenant/**"
            - ".github/workflows/deploy-tenant.yml"

jobs:
    deploy:
        runs-on: self-hosted
        environment: tenant-prod

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Deploy Tenant Service
              working-directory: ./api/v1/tenant
              env:
                  DOCKER_BUILDKIT: 1
                  COMPOSE_DOCKER_CLI_BUILD: 1
                  PORT: ${{ vars.PORT }}
                  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
                  POSTGRES_DB: ${{ vars.POSTGRES_DB }}
                  POSTGRES_USER: ${{ vars.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  RABBITMQ_PORT: ${{ vars.RABBITMQ_PORT }}
                  RABBITMQ_MGMT_PORT: ${{ vars.RABBITMQ_MGMT_PORT }}
                  RABBITMQ_USER: ${{ vars.RABBITMQ_USER }}
                  RABBITMQ_PASS: ${{ secrets.RABBITMQ_PASS }}
                  JWKS_URL: ${{vars.JWKS_URL}}
                  JWT_ISSUER: ${{vars.JWT_ISSUER}}
              run: |
                  docker network inspect kaditsm-network >/dev/null 2>&1 || docker network create kaditsm-network

                  docker compose up -d --build --wait --wait-timeout 60

                  docker image prune -f
